export const SystemErrorMessage = {
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  SERVICE_REQUEST_TIMEOUT: 'SERVICE_REQUEST_TIMEOUT',
} as const;

export const TokenErrorMessages = {
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_NOT_PROVIDED: 'TOKEN_NOT_PROVIDED',
  TOKEN_NOT_ACTIVE: 'TOKEN_NOT_ACTIVE',
  TOKEN_REVOKED: 'TOKEN_REVOKED',
}

export const ApiErrorMessages = {
  USER_ROLE_REQUIRED: 'USER_ROLE_REQUIRED',
  INSUFFICIENT_ROLE_PERMISSION: 'INSUFFICIENT_ROLE_PERMISSION',
  OWNER_APPLICATION_NOT_APPROVED: 'OWNER_APPLICATION_NOT_APPROVED',
} as const;
