export const SystemErrorMessage = {
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  SERVICE_REQUEST_TIMEOUT: 'SERVICE_REQUEST_TIMEOUT',
  IMAGE_UPLOAD_FAILED: 'IMAGE_UPLOAD_FAILED',
} as const;

export const TokenErrorMessages = {
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_NOT_PROVIDED: 'TOKEN_NOT_PROVIDED',
  TOKEN_NOT_ACTIVE: 'TOKEN_NOT_ACTIVE',
  TOKEN_REVOKED: 'TOKEN_REVOKED',
}

export const ApiErrorMessages = {
  USER_ROLE_REQUIRED: 'USER_ROLE_REQUIRED',
  INSUFFICIENT_ROLE_PERMISSION: 'INSUFFICIENT_ROLE_PERMISSION',
  OWNER_APPLICATION_NOT_APPROVED: 'OWNER_APPLICATION_NOT_APPROVED',
  AI_SEARCH_DAILY_QUOTA_EXHAUSTED: 'AI_SEARCH_DAILY_QUOTA_EXHAUSTED',
  IMAGE_FILE_REQUIRED: 'IMAGE_FILE_REQUIRED',
} as const;
