export const OwnerApplicationErrorMessages = {
  OWNER_APPLICATION_ALREADY_EXISTS: 'OWNER_APPLICATION_ALREADY_EXISTS',
  OWNER_APPLICATION_NOT_FOUND: 'OWNER_APPLICATION_NOT_FOUND',
  OWNER_APPLICATION_ALREADY_REVIEWED: 'OWNER_APPLICATION_ALREADY_REVIEWED',
  OWNER_APPLICATION_NOT_REJECTED:
    'Only rejected applications can be resubmitted',
} as const;

export const OwnershipClaimErrorMessages = {
  CLAIM_ALREADY_EXISTS: 'CLAIM_ALREADY_EXISTS',
  CLAIM_ALREADY_APPROVED: 'CLAIM_ALREADY_APPROVED',
  CLAIM_NOT_FOUND: 'CLAIM_NOT_FOUND',
  CLAIM_ALREADY_REVIEWED: 'CLAIM_ALREADY_REVIEWED',
} as const;

export const UserErrorMessages = {
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  PHONE_NUMBER_ALREADY_IN_USE: 'PHONE_NUMBER_ALREADY_IN_USE',
} as const;

export const FriendErrorMessages = {
  CANNOT_SEND_REQUEST_TO_SELF: 'CANNOT_SEND_REQUEST_TO_SELF',
  ALREADY_FRIENDS_WITH_USER: 'ALREADY_FRIENDS_WITH_USER',
  FRIEND_REQUEST_ALREADY_EXISTS: 'FRIEND_REQUEST_ALREADY_EXISTS',
  FRIEND_REQUEST_NOT_FOUND: 'FRIEND_REQUEST_NOT_FOUND',
  NOT_AUTHORIZED_TO_ACCEPT_REQUEST: 'NOT_AUTHORIZED_TO_ACCEPT_REQUEST',
  NOT_AUTHORIZED_TO_REJECT_REQUEST: 'NOT_AUTHORIZED_TO_REJECT_REQUEST',
  NOT_AUTHORIZED_TO_CANCEL_REQUEST: 'NOT_AUTHORIZED_TO_CANCEL_REQUEST',
  REQUEST_IS_NO_LONGER_VALID: 'REQUEST_IS_NO_LONGER_VALID',
  FRIENDSHIP_NOT_FOUND: 'FRIENDSHIP_NOT_FOUND',
} as const;

export const FavoriteErrorMessages = {
  PLACE_ALREADY_IN_FAVORITES: 'PLACE_ALREADY_IN_FAVORITES',
  FAVORITE_NOT_FOUND: 'FAVORITE_NOT_FOUND',
} as const;

export const PlaceErrorMessages = {
  INVALID_SORT_BY: 'INVALID_SORT_BY',
  INVALID_SORT_ORDER: 'INVALID_SORT_ORDER',
  EMBEDDING_SERVICE_UNAVAILABLE: 'EMBEDDING_SERVICE_UNAVAILABLE',
  PLACE_NOT_FOUND: 'PLACE_NOT_FOUND',
  PLACE_IMAGE_REQUIRED: 'PLACE_IMAGE_REQUIRED',
  PLACE_CATEGORY_NOT_FOUND: 'PLACE_CATEGORY_NOT_FOUND',
  PLACE_ATTRIBUTE_NOT_FOUND: 'PLACE_ATTRIBUTE_NOT_FOUND',
  INVALID_OPENING_HOUR_FORMAT: 'INVALID_OPENING_HOUR_FORMAT',
  INVALID_OPENING_HOUR_RANGE: 'INVALID_OPENING_HOUR_RANGE',
  DUPLICATED_OPENING_HOUR_DAY: 'DUPLICATED_OPENING_HOUR_DAY',
  INVALID_OPENING_HOUR_INTERVAL: 'INVALID_OPENING_HOUR_INTERVAL',
  PLACE_NOT_UNDER_REVIEW: 'PLACE_NOT_UNDER_REVIEW',
  PLACE_NOT_OWNER: 'PLACE_NOT_OWNER',
} as const;

export const S3ErrorMessages = {
  FILE_BODY_REQUIRED: 'FILE_BODY_REQUIRED',
  FAILED_TO_UPLOAD_FILE: 'FAILED_TO_UPLOAD_FILE',
} as const;

export const ImageErrorMessages = {
  invalidFileType: (allowedMimeTypes: string[]) =>
    `Invalid file type. Only ${allowedMimeTypes.join(', ')} are allowed`,
} as const;
