export const OwnerApplicationErrorMessages = {
  OWNER_APPLICATION_ALREADY_EXISTS: 'OWNER_APPLICATION_ALREADY_EXISTS',
  OWNER_APPLICATION_NOT_FOUND: 'OWNER_APPLICATION_NOT_FOUND',
  OWNER_APPLICATION_ALREADY_REVIEWED: 'OWNER_APPLICATION_ALREADY_REVIEWED',
} as const;
