export const GroupSessionMessages = {
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_NOT_ACTIVE: 'SESSION_NOT_ACTIVE',
  SESSION_ALREADY_ACTIVE: 'SESSION_ALREADY_ACTIVE',
  SESSION_ALREADY_CLOSED: 'SESSION_ALREADY_CLOSED',
  SHARE_CODE_GENERATION_FAILED: 'SHARE_CODE_GENERATION_FAILED',
  NOT_A_MEMBER: 'NOT_A_MEMBER',
  NOT_SESSION_CREATOR: 'NOT_SESSION_CREATOR',
  ALREADY_A_MEMBER: 'ALREADY_A_MEMBER',
  NICKNAME_REQUIRED: 'NICKNAME_REQUIRED',
  INVITE_FRIENDS_ONLY: 'INVITE_FRIENDS_ONLY',
  VOTE_ALREADY_FINALIZED: 'VOTE_ALREADY_FINALIZED',
  VOTE_REQUIRED_BEFORE_FINALIZE: 'VOTE_REQUIRED_BEFORE_FINALIZE',
  PLACE_NOT_FOUND: 'PLACE_NOT_FOUND',
  CATEGORY_LIMIT_EXCEEDED: 'CATEGORY_LIMIT_EXCEEDED',
  INVALID_SEARCH_RADIUS: 'INVALID_SEARCH_RADIUS',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  NOT_ENOUGH_MEMBERS_FOR_RECOMMENDATION:
    'NOT_ENOUGH_MEMBERS_FOR_RECOMMENDATION',
  RECOMMENDATION_EMPTY: 'RECOMMENDATION_EMPTY',
  CANDIDATE_NOT_FOUND: 'CANDIDATE_NOT_FOUND',
  NOT_CANDIDATE_OWNER: 'NOT_CANDIDATE_OWNER',
  CANNOT_LEAVE_AS_CREATOR: 'CANNOT_LEAVE_AS_CREATOR',
} as const;

export const GROUP_SESSION_SHARE_CODE_LENGTH = 6;
export const GROUP_SESSION_RECOMMENDATION_MIN_MEMBERS = 2;
export const GROUP_SESSION_DEFAULT_AUTO_CLOSE_DELAY_MINUTES = 10;
export const GROUP_SESSION_DEFAULT_SEARCH_RADIUS_KM = 5;
export const GROUP_SESSION_MIN_SEARCH_RADIUS_KM = 0.1;
export const GROUP_SESSION_MAX_SEARCH_RADIUS_KM = 100;
export const GROUP_SESSION_MAX_CATEGORY_COUNT = 5;
export const GROUP_SESSION_MAX_RECOMMENDATION_PLACES = 20;
export const GROUP_SESSION_RECOMMENDATION_TTL_SECONDS = 30;
