export const MAX_RECENT_SEARCHES_PER_USER = 3;
export const SEARCH_TRENDING_TTL_SECONDS = 5 * 60;
export const VECTOR_SIMILARITY_THRESHOLD = 0.35;
export const LLM_THINKING_TAG = '<think>';
export const MAX_SEARCH_RESULTS_PER_MODE = 500;
