export const INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';

export const AuthErrorMessages = {
  USERNAME_ALREADY_EXISTS: 'USERNAME_ALREADY_EXISTS',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  OWNER_APPLICATION_CREATE_FAILED: 'OWNER_APPLICATION_CREATE_FAILED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
} as const;

export const UserErrorMessages = {
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USERNAME_ALREADY_EXISTS: 'USERNAME_ALREADY_EXISTS',
  PHONE_NUMBER_ALREADY_IN_USE: 'PHONE_NUMBER_ALREADY_IN_USE',
} as const;
