export const AuthErrorMessages = {
  USERNAME_ALREADY_EXISTS: 'USERNAME_ALREADY_EXISTS',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  OWNER_APPLICATION_CREATE_FAILED: 'OWNER_APPLICATION_CREATE_FAILED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
} as const;
