export enum NotificationType {
  GROUP_INVITE = 'GROUP_INVITE',
  GROUP_VOTE_REMINDER = 'GROUP_VOTE_REMINDER',
  GROUP_VOTE_FINALIZED = 'GROUP_VOTE_FINALIZED',
  FRIEND_REQUEST = 'FRIEND_REQUEST',
  FRIEND_ACCEPTED = 'FRIEND_ACCEPTED',
  SYSTEM = 'SYSTEM',
  NEARBY_PLACE = 'NEARBY_PLACE',
  RECOMMENDATION = 'RECOMMENDATION',
  REVIEW_LOW_RATING = 'REVIEW_LOW_RATING',
}

export enum NotificationPreferredChannel {
  WEBSOCKET = 'WEBSOCKET',
  FCM = 'FCM',
  BOTH = 'BOTH',
}
